### ISSUE TITLE
版本异常+新功能建议

### ISSUE THREAD

**Issue by wwsuixin** [a1phaboy/nacosleak#1]
首先感谢大佬的无私分享，
另外想咨询一下大佬是否有时间增加一个输出到指定位置的功能呢
还有就是发现下载的releases 1.4版本 但是运行提示是1.3  似乎与提交的代码不太相符

**Comment by a1phaboy** [comment]
在下版本会考虑加入指定目录；
这个可能是banner忘记改了，不影响正常使用

**Comment by a1phaboy** [comment]
已更新
